server:
  servlet-path: /rest/
  port: 8081

# Get a new token from: https://developer.spotify.com/web-api/console/get-search-item/
# Replace the token below with your new token
token: "BQAVcfrnLlabr2Bd_QbLCru-htyWiGETq5LqH-hbNHocaDRiR5S7bZlKaapBDqErcL70i85dVTS5u1OxXf0kOOLm9rFPo9uZOiIk98jbVoazROdzTp5Oy_98Tc0CohHn44DcsJndQAQ"