server:
  servlet-path: /rest/
  port: 8081

# Get a new token from: https://developer.spotify.com/web-api/console/get-search-item/
# Replace the token below with your new token
token: "BQCr4pkcgG6sK8EFWC3ujKQbtHHKc0oo2QQ0l3Ig4ycTobP6dWHdtpRdmFnuysIEng9HVKDC2qm7D7kW-Z-RxOCgQyYwPq-wsXZo6XlCwESM6Mt1Qv-X7AernRPUjxDqhjWrijv0jkM"